name: Android CI (Windows)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install npm packages
        run: npm install

      - name: Run tests
        run: npm test

      - name: Setup Java (required for Android)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build Android release APK
        working-directory: android
        run: gradlew.bat assembleRelease
        shell: cmd

      # - name: Upload release APK
      #   uses: actions/upload-artifact@v3.1.3
      #   with:
      #     name: release-apk
      #     path: android\app\build\outputs\apk\release\app-release.apk
